authentication:
  use_authent: ${ARLAS_USE_AUTHENT}
  auth_mode: ${ARLAS_AUTHENT_MODE}
  force_connect: false
  use_discovery: false
  threshold: ${ARLAS_AUTHENT_THRESHOLD}
  url: ${ARLAS_IAM_SERVER_URL}
